name: CI DevOps 2024

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Étape 2 : Configurer JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # Étape 3 : Construire, tester et analyser avec SonarCloud
      - name: Build, test, and analyze with SonarCloud
        working-directory: ./simple-api # Changez ce répertoire si nécessaire
        run: |
          mvn -B verify sonar:sonar \
            -Dsonar.projectKey=tonyeessome_devops-livecoding \
            -Dsonar.organization=tonyeessome \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
